GET https://congenial-waddle-5g4r7w9p54grh79qg-3000.app.github.dev/

###

POST https://congenial-waddle-5g4r7w9p54grh79qg-3000.app.github.dev/api/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "emaiil@gmail.com",
  "password": "testpassword"
}

###
POST https://congenial-waddle-5g4r7w9p54grh79qg-3000.app.github.dev/api/auth/login
Content-Type: application/json

{
  "email": "emaiil@gmail.com",
  "password": "testpassword"
}

###
GET https://congenial-waddle-5g4r7w9p54grh79qg-3000.app.github.dev/dashboard

###

POST  http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJlbWFpaWxAZ21haWwuY29tIiwiaWF0IjoxNzcyMDM4NzcwLCJleHAiOjE3NzI2NDM1NzB9.C1VekPH6Esuo5zLtlSVqrnJhhcR02H3dp7daLCBbBmQ

{
  "title": "Build SaaS SaaSur",
  "description": "Finish full stack app",
  "priority": "high"
}


